# Mini Projeto — Analista de Dados do Banco Fácil 🏦 - Felipe de Oliveira de Moraes

**Contexto:** Você é analista de dados do Banco Fácil. O banco te enviou uma tabela de transações e uma tabela de cadastro de clientes. Seu trabalho é cruzar essas bases e gerar uma análise rápida.

**Data limite da entrega: ** 10/05/2026

**Entrega: ** Subir na plataforma LMS o arquivo Jupyter Notebook (.ipynb)

In [1]:
import pandas as pd
import numpy as np

# Base de transações
transacoes = pd.DataFrame({
    'id_cliente': [1, 2, 1, 3, 2, 1, 3, 2],
    'tipo':       ['Crédito', 'Débito', 'Débito', 'Crédito', 'Crédito', 'Débito', 'Débito', 'Crédito'],
    'categoria':  ['Salário', 'Alimentação', 'Transporte', 'Salário', 'Lazer', 'Alimentação', 'Transporte', 'Salário'],
    'valor':      [3200.0, 150.0, None, 4500.0, 200.0, 80.0, None, 2800.0],
    'canal':      ['App', 'Agência', 'App', 'Internet Banking', 'App', 'Agência', 'App', 'Internet Banking']
})

# Base de cadastro de clientes
clientes = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4],
    'nome':       ['Ana', 'Bruno', 'Carlos', 'Diana'],
    'estado':     ['SP', 'RJ', 'MG', 'SP'],
    'perfil':     ['Premium', 'Básico', 'Intermediário', 'Básico']
})

### Tarefa 1 — Conheça os dados

Use `shape`, `dtypes`, `head()` e `isna().sum()` nas **duas** tabelas separadamente.

- Quantos clientes existem no cadastro?
- Quantas transações existem?
- Alguma coluna possui valores nulos?

In [11]:
# Exibindo as formas dos DataFrames
print("Shape do df transacoes:", transacoes.shape)
print("Shape do df clientes:", clientes.shape)

# Exibindo as primeiras linhas dos DataFrames
print("\nPrimeiras linhas do df transacoes:")
display(transacoes.head())
print("\nPrimeiras linhas do df clientes:")
display(clientes.head())

# Verificando tipos de dados
print("\nTipos de dados do df transacoes:")
print(transacoes.dtypes)
print("\nTipos de dados do df clientes:")
print(clientes.dtypes)

# Verificando valores ausentes
print("\nValores ausentes no df transacoes:")
print(transacoes.isnull().sum())
print("\nValores ausentes no df clientes:")
print(clientes.isnull().sum())

# Respostas:
print("\nRespostas:")
print("Existem 4 clientes no cadastro")
print("Existem 8 transações registradas")
print("A coluna 'valor' do df transacoes possui 2 valores ausentes")

Shape do df transacoes: (8, 5)
Shape do df clientes: (4, 4)

Primeiras linhas do df transacoes:

   id_cliente     tipo    categoria   valor             canal
0           1  Crédito      Salário  3200.0               App
1           2   Débito  Alimentação   150.0           Agência
2           1   Débito   Transporte     NaN               App
3           3  Crédito      Salário  4500.0  Internet Banking
4           2  Crédito        Lazer   200.0               App

Primeiras linhas do df clientes:

   id_cliente    nome estado         perfil
0           1     Ana     SP        Premium
1           2   Bruno     RJ         Básico
2           3  Carlos     MG  Intermediário
3           4   Diana     SP         Básico

Tipos de dados do df transacoes:
id_cliente      int64
tipo              str
categoria         str
valor         float64
canal             str
dtype: object

Tipos de dados do df clientes:
id_cliente    int64
nome            str
estado          str
perfil          str
dtype: object

Valores ausentes no df transacoes:
id_cliente    0
tipo          0
categoria     0
valor         2
canal         0
dtype: int64

Valores ausentes no df clientes:
id_cliente    0
nome          0
estado        0
perfil        0
dtype: int64

Respostas:
Existem 4 clientes no cadastro
Existem 8 transações registradas
A coluna 'valor' do df transacoes possui 2 valores ausentes

### Tarefa 2 — Limpeza

Preencha os valores nulos da coluna `valor` com a **mediana geral** da coluna.  
Use `fillna()`.

Confirme que não existem mais nulos com `isna().sum()`.

In [17]:
# Preenchendo os valores ausentes na coluna 'valor' com a mediana geral da coluna
transacoes_ajustado = transacoes.fillna(transacoes['valor'].median())
print("\nTransações ajustadas (com valores ausentes preenchidos):")
display(transacoes_ajustado)

# Conferindo o resultado do preenchimento
print("\nValores ausentes após preenchimento:")
print(transacoes_ajustado.isna().sum())

Transações ajustadas (com valores ausentes preenchidos):

   id_cliente     tipo    categoria   valor             canal
0           1  Crédito      Salário  3200.0               App
1           2   Débito  Alimentação   150.0           Agência
2           1   Débito   Transporte  1500.0               App
3           3  Crédito      Salário  4500.0  Internet Banking
4           2  Crédito        Lazer   200.0               App
5           1   Débito  Alimentação    80.0           Agência
6           3   Débito   Transporte  1500.0               App
7           2  Crédito      Salário  2800.0  Internet Banking

Valores ausentes após preenchimento:
id_cliente    0
tipo          0
categoria     0
valor         0
canal         0
dtype: int64

### Tarefa 3 — Cálculos com NumPy

Com os valores da coluna `valor` (já limpa), crie um array NumPy e calcule:

- Soma total das transações
- Valor médio
- Maior valor
- Menor valor

In [ ]:
# Analisando as transações ajustadas
array = transacoes_ajustado['valor'].values
print(array, "\n")
print("Soma total das transações:", np.sum(array))
print("Valor médio das transações:", np.mean(array))
print("Maior valor das transações:", np.max(array))
print("Menor valor das transações:", np.min(array))

SyntaxError: invalid syntax (2453626677.py, line 3)